import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import "./globals.css";
import { Chat } from "@/components/Chat";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Chat />
        {children}
      </body>
    </html>
  );
}
